# Генерация тестовых данных

In [10]:
import copy
# import networkx as nx
import scipy as sp
import matplotlib.pyplot as plt
import numpy as np
import random
import sklearn
from sklearn.cluster import AgglomerativeClustering
from sklearn.cluster import KMeans

import matplotlib.pyplot as plt
import math

import warnings
warnings.filterwarnings('ignore')

In [11]:
list_of_num_vertices = np.array([1000])
list_of_num_clusters = np.array([3, 7, 15, 25])
list_of_probability_out = np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7])
num_tests = 1
num_viborka = 100

In [12]:
my_random_seed = 23
np.random.seed(my_random_seed)

In [13]:
def get_random_list_with_sum(lenth, total_sum):
    full_rand = np.random.rand(lenth)
    full_rand /= np.sum(full_rand)
    full_rand *= total_sum
    full_rand = full_rand.astype(int)
    full_rand[np.where(full_rand == 0)[0]] += 1
    diff = total_sum - np.sum(full_rand)
#     print(diff)
    if (diff >= 0):
        full_rand[-1] += diff
    else:
        full_rand[np.where(full_rand > diff)[0][0]] += diff
    return full_rand

In [14]:
def get_good_list_of_list(vec_nums):
    answer = []
    start = 1
    for el in vec_nums:
        row = np.arange(start, start + el, 1)
        start += el
        answer.append(row)
    return answer

In [15]:
def get_viborka(correct, probability):
    all_len = len(correct)
    append_list = []
    for i in range(len(correct)):
        prob = np.random.rand(len(correct[i]))
        index = np.where(probability >= prob)[0]
        append_list.append(correct[i][index])
        correct[i] = np.delete(correct[i], index)
    idi = 0
#     print(append_list)
    for row in append_list:
        for el in row:
            index = np.random.randint(all_len)
            while (index == idi):
                index = np.random.randint(all_len)
            correct[index] = np.append(correct[index], el)
        idi += 1
    return correct

In [16]:
def print_list_of_list(v, f):
    for raw in v:
        for el in raw:
            f.write(str(el) + ' ')
        f.write('\n')
    return

In [17]:
for test in range(num_tests, 51):
    for num_ver in list_of_num_vertices:
#         print(len(list_of_num_clusters))
        for num_cl in list_of_num_clusters:
            vec_nums = get_random_list_with_sum(num_cl, num_ver)
            correct = get_good_list_of_list(vec_nums)

#             print(len(list_of_probability_out))
            for prob in list_of_probability_out:
                name = '/Users/ilnurbaykov/HomeWork/diplom/tests/' + f'clusters{num_cl}/' + f'prob0_{int(prob * 100)}/' + f'test_{test}.txt' 
                f = open(name, 'w+')
#                 print(name)
                f.write(str(num_cl) + '\n')
                print_list_of_list(correct, f)
                f.write(str(prob) + '\n')
                f.write(str(num_viborka) + '\n')
                for num_of_viborka in range(num_viborka):
                    my_deepcopy = copy.deepcopy(correct)
                    viborka = get_viborka(my_deepcopy, prob)
                    print_list_of_list(viborka, f)
                f.close()

In [78]:
pwd

'/Users/ilnurbaykov/HomeWork/diplom'

In [ ]:
+ f'prob0_{int(prob * 100)}/' 

In [53]:
a = np.array([1, 2, 3])
a = a.reshape(1, 3)
b = np.array([1, 2, 3])
b = b.reshape(3, 1)
print(a, b)
print(a *  b)


[[1 2 3]] [[1]
 [2]
 [3]]
[[1 2 3]
 [2 4 6]
 [3 6 9]]
